name: CI

on:
  pull_request:
    branches:
      - main
concurrency:
  group: ci-tests-${{github.ref}}-1
  cancel-in-progress: true


jobs:
  echo-output:
    uses: marten-soderquist/github-actions-tut/.github/workflows/_echo.yaml@test
    with:
      message: 'Det funkar'
  lint-test:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint:ci

     

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Cache yarn depenedencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache.Cypress
            **/node_modules
          key: our-cache-yarn-${{ hashFiles('**/yarn.lock.json')}}


      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Test
        run: yarn test:ci
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install
       

      - name: e2e
        run: yarn e2e